// apps/test-app-angular/src/app/app.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { SwipeEvent } from 'ng-swipe';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styles: [],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  onSwipeEnd(event: SwipeEvent) {
    console.log(`SwipeEnd direction: ${event.direction} and distance: ${event.distance}`);
  }
}

<div style="text-align: center">
  <h1 ngSwipe (swipeEnd)="onSwipeEnd($event)">Welcome to Test app!</h1>
</div>

// apps/test-app-react/src/app/app.tsx
import { SwipeEvent, useSwipe } from '@ag/swipe-react';

export function App() {
  const swipeElement = useSwipe({
    onSwipeEnd: (event: SwipeEvent) => {
      console.log(`SwipeEnd direction: ${event.direction} and distance: ${event.distance}`);
    }
  });

  return <div ref={swipeElement}>Swipe me!</div>
}

export default App;
