// apps/test-app-react/src/app/app.tsx
import { SwipeEvent, useSwipe } from '@ag/swipe-react';

export function App() {
  const swipeElement = useSwipe({
    onSwipeEnd: (event: SwipeEvent) => {
      console.log(`SwipeEnd direction: ${event.direction} and distance: ${event.distance}`);
    }
  });

  return <div ref={swipeElement}>Swipe me!</div>
}

export default App;

// apps/test-app/src/app/app.component.ts
import { SwipeEvent } from '@swipe/swipe-core';
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styles: [],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AppComponent {
  onSwipeEnd(event: SwipeEvent) {
    console.log(event);
  }
}
